---
- name: Patch Ubuntu Server
  hosts: all
  become: yes
  vars:
    reboot_required_file: /var/run/reboot-required
  
  pre_tasks:
    - name: Ensure python3-apt is installed
      ansible.builtin.raw: sudo apt-get install -y python3-apt
      register: python3_apt_install
      changed_when: "'Setting up python3-apt' in python3_apt_install.stdout"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      register: update_result

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      register: upgrade_result

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: "{{ reboot_required_file }}"
      register: reboot_required

    - name: Reboot the server if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after patching"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists

    - name: Show update result
      ansible.builtin.debug:
        var: update_result

    - name: Show upgrade result
      ansible.builtin.debug:
        var: upgrade_result

    - name: Show reboot status
      ansible.builtin.debug:
        msg: "Reboot was {{ 'required and performed' if reboot_required.stat.exists else 'not required' }}"
