---
- name: Patch RHEL systems excluding Java and log output (Auto Reboot)
  hosts: all
  become: yes
  vars:
    patch_log: /var/log/ansible-patch.log

  tasks:

    - name: Update all packages except Java
      ansible.builtin.shell: |
        yum update -y --exclude=java* --exclude=openjdk* | tee {{ patch_log }}
      args:
        warn: false

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        register: reboot_required

    - name: Reboot the server if needed
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after patching"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists

    - name: Display patch log
      ansible.builtin.shell: cat {{ patch_log }}
      register: patch_output
      changed_when: false

    - name: Show patch output
      ansible.builtin.debug:
        var: patch_output.stdout_lines
